schema-version = 2
release-version = "10.4.1"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.64.0"
vendor = "bottlerocket"
