[package]
name = "strace"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://strace.io/files"

[[package.metadata.build-package.external-files]]
url = "https://strace.io/files/6.11/strace-6.11.tar.xz"
sha512 = "c639ae7097d418f8b815bd008de9423079dad70829a5eb392d3c5def81243b8a9133c10251a7c00a4991f580cff5b62466f8b53b4b8e425a009548fb3582bdb0"

[build-dependencies]
glibc = { path = "../glibc" }
