[package]
name = "cfsignal"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[features]
fips = ["aws-smithy-http-client/rustls-aws-lc-fips"]

[dependencies]
aws-config.workspace = true
aws-sdk-cloudformation.workspace = true
aws-smithy-http-client = { workspace = true, features = ["rustls-aws-lc"] }
aws-types.workspace = true
imdsclient.workspace = true
log.workspace = true
bottlerocket-crypto-provider.workspace = true
serde = { workspace = true, features = ["derive"] }
simplelog.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml.workspace = true

[build-dependencies]
generate-readme.workspace = true
