[Service]
Environment=ACTIVE_SNAPSHOTTER=overlayfs
EnvironmentFile=-/var/cache/containerd/active-snapshotter

# load the built-in pause image
ExecStartPre=/usr/bin/ctr \
    --namespace=k8s.io \
    image import \
    --snapshotter=${ACTIVE_SNAPSHOTTER} \
    --local \
    --all-platforms \
    /usr/libexec/kubernetes/kubernetes-pause.tar

# label it to prevent it from being removed
ExecStartPre=/usr/bin/ctr \
    --namespace=k8s.io \
    image label \
    localhost/kubernetes/pause:0.1.0 \
    io.cri-containerd.pinned=pinned
