[package]
name = "iputils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/iputils/iputils/releases"

[[package.metadata.build-package.external-files]]
path = "iputils-20240905.tar.gz"
url = "https://github.com/iputils/iputils/archive/20240905.tar.gz"
sha512 = "7f7d04c22e533d71bc54ea05459724c9d47068ba77fa0a49a520b0273fe5baef8b997b50d9c30d781be98b4932d4543ccbe6f69e05c8feb12d858df8b82ae445"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
