[package]
name = "migrator"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[features]
fips = ["tough/fips"]

[dependencies]
aws-lc-rs = { workspace = true, features = ["bindgen"] }
bottlerocket-release.workspace = true
bytes.workspace = true
futures = { workspace = true, features = ["default"] }
futures-core.workspace = true
log.workspace = true
lz4.workspace = true
nix.workspace = true
pentacle.workspace = true
rand = { workspace = true, features = ["std", "std_rng"] }
semver.workspace = true
simplelog.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["compat", "io-util"] }
tough = { workspace = true }
update_metadata.workspace = true
url.workspace = true

[build-dependencies]
generate-readme.workspace = true

[dev-dependencies]
chrono = { workspace = true, features = ["clock", "std"] }
storewolf.workspace = true
tempfile.workspace = true

[[bin]]
name = "migrator"
path = "src/main.rs"
