[package]
name = "libaudit"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-audit/audit-userspace/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-audit/audit-userspace/archive/v3.1.5/audit-userspace-3.1.5.tar.gz"
sha512 = "9274a6addf20f306292e0a79f3432b7f4934b8134ed9cafdd2088ec676c03303e56f1c618b45fc922d4484306801dcbec420ea6533f68a1464960b979d40313a"

[build-dependencies]
glibc = { path = "../glibc" }
