[Unit]
# mount the LUKS mapper instead of the raw partition and only after the
# partition has been encrypted, unlocked and formatted.
After=unlock-private-fs.service prepare-private-fs.service
Requires=prepare-private-fs.service

[Mount]
What=/dev/mapper/BOTTLEROCKET-PRIVATE
