[Service]
# In case of ephemeral-encryption-keys, we format the BOTTLEROCKET-PRIVATE with
# `encrypt` feature flag. So, we drop the tune2fs call, which is used to enable
# the flag and generate the key and encrypt the datastore.
ExecStart=
ExecStart=/usr/bin/rottweiler generate-key datastore
ExecStart=/usr/bin/rottweiler encrypt directory ${DATASTORE_DIR} datastore
