d /etc/deprecated-settings 0700 root root -
d /var/log/kdump 0700 root root -
T /var/log/kdump - - - - security.selinux=system_u:object_r:secret_t:s0
d /var/lib/systemd/pstore 0700 root root -
T /var/lib/systemd/pstore - - - - security.selinux=system_u:object_r:secret_t:s0
