[Service]
# With ephemeral-encryption-keys, the DATA partition grow and dm-crypt mapper resize
# happen in encrypt-unlock-local-fs.service; override repart with a no-op.
ExecStart=
ExecStart=/usr/bin/true
