[Service]
EnvironmentFile=/usr/share/bottlerocket/image-features.env
# Delete the sealed data-partition encryption key after it has been used for the
# time in the boot, forcing format and fresh key generation in the next boot.
ExecStartPost=/usr/bin/rottweiler delete-key bottlerocket-data
