[Service]
# Delete the key used to encrypt the datastore after it has been used for the final
# time in the boot, forcing new key generation and a complete rebuild of the datastore
# in the subsequent boot.
ExecStartPost=/usr/bin/rottweiler delete-key datastore
